SET ROLE talus_fn;
CREATE TABLE app.customer_profile(tenant_id uuid NOT NULL,customer_profile_id uuid NOT NULL,customer_id uuid NOT NULL,email text NOT NULL,full_name text NOT NULL,phone text,driver_license_hash text,license_verified_at timestamptz,PRIMARY KEY(tenant_id,customer_profile_id),UNIQUE(tenant_id,customer_id),FOREIGN KEY(tenant_id,customer_id) REFERENCES app.customer(tenant_id,customer_id));
CREATE TABLE app.booking_driver(tenant_id uuid NOT NULL,booking_item_id uuid NOT NULL,customer_id uuid NOT NULL,is_primary boolean NOT NULL DEFAULT false,PRIMARY KEY(tenant_id,booking_item_id,customer_id),FOREIGN KEY(tenant_id,booking_item_id) REFERENCES app.booking_item(tenant_id,booking_item_id),FOREIGN KEY(tenant_id,customer_id) REFERENCES app.customer(tenant_id,customer_id));
CREATE TABLE app.executed_waiver(tenant_id uuid NOT NULL,executed_waiver_id uuid NOT NULL,customer_id uuid NOT NULL,booking_item_id uuid NOT NULL,waiver_policy_version_id uuid NOT NULL,signed_at timestamptz NOT NULL,signer_name text NOT NULL,signer_ip inet,signature_ref text NOT NULL,agreement_hash text NOT NULL,PRIMARY KEY(tenant_id,executed_waiver_id),UNIQUE(tenant_id,customer_id,booking_item_id,waiver_policy_version_id),FOREIGN KEY(tenant_id,customer_id) REFERENCES app.customer(tenant_id,customer_id),FOREIGN KEY(tenant_id,booking_item_id) REFERENCES app.booking_item(tenant_id,booking_item_id),FOREIGN KEY(tenant_id,waiver_policy_version_id) REFERENCES app.tenant_waiver_policy(tenant_id,tenant_waiver_policy_id));
CREATE TRIGGER m10_waiver_append BEFORE UPDATE OR DELETE ON app.executed_waiver FOR EACH ROW EXECUTE FUNCTION app.enforce_append_only();
CREATE OR REPLACE FUNCTION app.execute_digital_waiver(p_id uuid,p_customer uuid,p_item uuid,p_policy uuid,p_name text,p_ip inet,p_ref text,p_hash text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=app,pg_catalog AS $$ DECLARE t uuid:=app.current_context_tenant_id();BEGIN PERFORM app.require_context();INSERT INTO app.executed_waiver VALUES(t,p_id,p_customer,p_item,p_policy,clock_timestamp(),p_name,p_ip,p_ref,p_hash);PERFORM app.append_audit('waiver.executed','executed_waiver',p_id);RETURN p_id;END;$$;
DO $$ DECLARE x text;BEGIN FOREACH x IN ARRAY ARRAY['customer_profile','booking_driver','executed_waiver'] LOOP EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY;ALTER TABLE app.%I FORCE ROW LEVEL SECURITY;CREATE POLICY tenant_context_policy ON app.%I USING(tenant_id=app.current_context_tenant_id() AND app.context_is_valid()) WITH CHECK(tenant_id=app.current_context_tenant_id() AND app.context_is_valid())',x,x,x);END LOOP;END;$$;
REVOKE ALL ON app.customer_profile,app.booking_driver,app.executed_waiver FROM PUBLIC,talus_staff,talus_api,talus_customer;
RESET ROLE;
