SET ROLE talus_fn;
ALTER TABLE app.audit_event ADD COLUMN previous_event_hash text;
ALTER TABLE app.audit_event ADD COLUMN event_hash text;
CREATE UNIQUE INDEX audit_event_tenant_hash_uq ON app.audit_event(tenant_id,event_hash) WHERE event_hash IS NOT NULL;
CREATE OR REPLACE FUNCTION app.append_audit(p_action text,p_resource_type text,p_resource_id uuid,p_operation_id uuid DEFAULT NULL,p_details jsonb DEFAULT '{}'::jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=app,pg_catalog AS $$ DECLARE v_event uuid;v_prev text;v_at timestamptz:=clock_timestamp();v_hash text;BEGIN PERFORM app.require_context();PERFORM pg_advisory_xact_lock(hashtextextended(app.current_context_tenant_id()::text,0));SELECT event_hash INTO v_prev FROM app.audit_event WHERE tenant_id=app.current_context_tenant_id() AND event_hash IS NOT NULL ORDER BY occurred_at DESC,audit_event_id DESC LIMIT 1;v_prev:=COALESCE(v_prev,repeat('0',64));v_hash:=encode(digest(v_prev||app.current_context_tenant_id()::text||p_action||COALESCE(app.current_context_principal_id()::text,'')||p_details::text||v_at::text,'sha256'),'hex');INSERT INTO app.audit_event(tenant_id,actor_principal_id,action,resource_type,resource_id,operation_id,details,occurred_at,previous_event_hash,event_hash) VALUES(app.current_context_tenant_id(),app.current_context_principal_id(),p_action,p_resource_type,p_resource_id,p_operation_id,p_details,v_at,v_prev,v_hash) RETURNING audit_event_id INTO v_event;RETURN v_event;END;$$;
CREATE OR REPLACE FUNCTION app.verify_audit_chain(p_from_timestamp timestamptz DEFAULT NULL,p_to_timestamp timestamptz DEFAULT NULL) RETURNS TABLE(is_valid boolean,broken_event_id uuid,error_reason text,events_verified integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=app,pg_catalog AS $$ DECLARE r record;prev text:=repeat('0',64);expected text;n integer:=0;BEGIN PERFORM app.require_staff_role('staff');FOR r IN SELECT * FROM app.audit_event WHERE tenant_id=app.current_context_tenant_id() AND event_hash IS NOT NULL AND (p_from_timestamp IS NULL OR occurred_at>=p_from_timestamp) AND (p_to_timestamp IS NULL OR occurred_at<p_to_timestamp) ORDER BY occurred_at,audit_event_id LOOP expected:=encode(digest(prev||r.tenant_id::text||r.action||COALESCE(r.actor_principal_id::text,'')||r.details::text||r.occurred_at::text,'sha256'),'hex');IF r.previous_event_hash<>prev OR r.event_hash<>expected THEN RETURN QUERY SELECT false,r.audit_event_id,'hash mismatch',n;RETURN;END IF;prev:=r.event_hash;n:=n+1;END LOOP;RETURN QUERY SELECT true,NULL::uuid,NULL::text,n;END;$$;
REVOKE ALL ON FUNCTION app.verify_audit_chain(timestamptz,timestamptz) FROM PUBLIC,talus_customer,talus_device;
GRANT EXECUTE ON FUNCTION app.verify_audit_chain(timestamptz,timestamptz) TO talus_staff,talus_api;
RESET ROLE;
