SET ROLE talus_fn;
GRANT CREATE ON SCHEMA app TO talus_public_fn;
SET ROLE talus_public_fn;
CREATE OR REPLACE FUNCTION app.create_public_reservation(p_customer uuid,p_category_location uuid,p_start timestamptz,p_end timestamptz) RETURNS TABLE(booking_id uuid,booking_item_id uuid,access_token uuid) LANGUAGE plpgsql SECURITY DEFINER SET search_path=app,pg_catalog AS $$
#variable_conflict use_variable
DECLARE v_tenant_id uuid;v_booking_id uuid:=gen_random_uuid();v_item_id uuid:=gen_random_uuid();v_terms_id uuid:=gen_random_uuid();v_item_terms_id uuid:=gen_random_uuid();v_token uuid:=gen_random_uuid();v_location_id uuid;
BEGIN SELECT cl.tenant_id,cl.location_id INTO v_tenant_id,v_location_id FROM app.category_location AS cl WHERE cl.category_location_id=p_category_location AND cl.active LIMIT 1;IF v_tenant_id IS NULL OR p_end<=p_start OR NOT EXISTS(SELECT 1 FROM app.customer AS c WHERE c.tenant_id=v_tenant_id AND c.customer_id=p_customer) THEN RAISE EXCEPTION 'PUBLIC_RESERVATION_INPUT_INVALID' USING ERRCODE='P0001';END IF;INSERT INTO app.booking(tenant_id,booking_id,booking_reference,pickup_location_id,return_location_id,state)VALUES(v_tenant_id,v_booking_id,'WEB-'||substr(v_booking_id::text,1,8),v_location_id,v_location_id,'draft');INSERT INTO app.booking_terms_revision(tenant_id,booking_terms_revision_id,booking_id,revision_number)VALUES(v_tenant_id,v_terms_id,v_booking_id,1);INSERT INTO app.booking_item(tenant_id,booking_item_id,booking_id,item_number,state)VALUES(v_tenant_id,v_item_id,v_booking_id,1,'reserved');INSERT INTO app.booking_item_terms_revision(tenant_id,booking_item_terms_revision_id,booking_item_id,booking_id,booking_terms_revision_id,category_location_id,revision_number,scheduled_start_at,scheduled_end_at,chargeable_day_count)VALUES(v_tenant_id,v_item_terms_id,v_item_id,v_booking_id,v_terms_id,p_category_location,1,p_start,p_end,GREATEST(1,p_end::date-p_start::date));UPDATE app.booking_item AS bi SET current_terms_revision_id=v_item_terms_id WHERE bi.tenant_id=v_tenant_id AND bi.booking_item_id=v_item_id;INSERT INTO app.booking_customer VALUES(v_tenant_id,v_booking_id,p_customer);INSERT INTO app.customer_booking_access_token(tenant_id,booking_id,booking_item_id,customer_id,token_hash,expires_at)VALUES(v_tenant_id,v_booking_id,v_item_id,p_customer,public.digest(v_token::text,'sha256'),clock_timestamp()+interval '48 hours');RETURN QUERY SELECT v_booking_id,v_item_id,v_token;END;$$;
RESET ROLE;
SET ROLE talus_fn;
REVOKE CREATE ON SCHEMA app FROM talus_public_fn;
RESET ROLE;
